/** 고덕 city 파라미터용 — LLM 없이 로컬로 처리해 토큰 절약 */
export const CITIES = [
  { value: "", label: "전체(중국)", short: "전체" },
  { value: "北京", label: "베이징 · 北京", short: "베이징" },
  { value: "上海", label: "상하이 · 上海", short: "상하이" },
  { value: "广州", label: "광저우 · 广州", short: "광저우" },
  { value: "深圳", label: "선전 · 深圳", short: "선전" },
  { value: "成都", label: "청두 · 成都", short: "청두" },
  { value: "杭州", label: "항저우 · 杭州", short: "항저우" },
  { value: "重庆", label: "충칭 · 重庆", short: "충칭" },
  { value: "西安", label: "시안 · 西安", short: "시안" },
  { value: "南京", label: "난징 · 南京", short: "난징" },
  { value: "武汉", label: "우한 · 武汉", short: "우한" },
  { value: "苏州", label: "쑤저우 · 苏州", short: "쑤저우" },
  { value: "天津", label: "톈진 · 天津", short: "톈진" },
  { value: "青岛", label: "칭다오 · 青岛", short: "칭다오" },
  { value: "厦门", label: "샤먼 · 厦门", short: "샤먼" },
  { value: "昆明", label: "쿤밍 · 昆明", short: "쿤밍" },
  { value: "大连", label: "다롄 · 大连", short: "다롄" },
  { value: "哈尔滨", label: "하얼빈 · 哈尔滨", short: "하얼빈" },
] as const;
